name = "pika-wiki"
main = ".open-next/worker.js"
compatibility_date = "2025-01-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[observability]
enabled = true

[[r2_buckets]]
binding = "WIKI_DOCS"
bucket_name = "pika-wiki-docs"

[env.production]
[[env.production.r2_buckets]]
binding = "WIKI_DOCS"
bucket_name = "pika-wiki-docs-prod"